filtered_cols = [
    "home_points_pct",
    "home_win_pct",
    "home_draw_pct",
    "home_loss_pct",
    "home_points_pct_last_games",
    "home_win_pct_last_games",
    "home_draw_pct_last_games",
    "home_loss_pct_last_games",
    "home_home_win_pct",
    "home_home_draw_pct",
    "home_home_loss_pct",
    "home_team_xg",
    "home_team_score",
    "home_opp_score",
    "home_opp_xg",
    "home_team_Sh",
    "home_team_SoT",
    "home_team_SoT%",
    "home_team_G/Sh",
    "home_team_G/SoT",
    "home_team_Dist",
    # 'home_team_npxG',
    # 'home_team_npxG/Sh',
    # 'home_team_G-xG',
    # 'home_team_np:G-xG',
    # 'home_team_Att',
    # 'home_team_Cmp',
    "home_team_TB",
    # 'home_team_Sw',
    # 'home_team_Crs',
    # 'home_team_CK',
    "home_team_SCA",
    "home_team_Poss",
    "home_team_Succ",
    "home_team_Succ%",
    # 'home_team_CrdY',
    # 'home_team_CrdR',
    "home_team_Recov",
    "home_opp_Sh",
    "home_opp_SoT",
    "home_opp_SoT%",
    "home_opp_G/Sh",
    "home_opp_G/SoT",
    "home_opp_Dist",
    # 'home_opp_npxG',
    # 'home_opp_npxG/Sh',
    # 'home_opp_G-xG',
    # 'home_opp_np:G-xG',
    # 'home_opp_Att',
    # 'home_opp_Cmp',
    "home_opp_TB",
    # 'home_opp_Sw',
    # 'home_opp_Crs',
    # 'home_opp_CK',
    "home_opp_SCA",
    "home_opp_Poss",
    "home_opp_Succ",
    "home_opp_Succ%",
    # 'home_opp_CrdY',
    # 'home_opp_CrdR',
    "home_opp_Recov",
    "away_points_pct",
    "away_win_pct",
    "away_draw_pct",
    "away_loss_pct",
    "away_points_pct_last_games",
    "away_win_pct_last_games",
    "away_draw_pct_last_games",
    "away_loss_pct_last_games",
    "away_away_win_pct",
    "away_away_draw_pct",
    "away_away_loss_pct",
    "away_team_xg",
    "away_team_score",
    "away_opp_score",
    "away_opp_xg",
    "away_team_Sh",
    "away_team_SoT",
    "away_team_SoT%",
    "away_team_G/Sh",
    "away_team_G/SoT",
    "away_team_Dist",
    # 'away_team_npxG',
    # 'away_team_npxG/Sh',
    # 'away_team_G-xG',
    # 'away_team_np:G-xG',
    # 'away_team_Att',
    # 'away_team_Cmp',
    "away_team_TB",
    # 'away_team_Sw',
    # 'away_team_Crs',
    # 'away_team_CK',
    "away_team_SCA",
    "away_team_Poss",
    "away_team_Succ",
    "away_team_Succ%",
    # 'away_team_CrdY',
    # 'away_team_CrdR',
    "away_team_Recov",
    "away_opp_Sh",
    "away_opp_SoT",
    "away_opp_SoT%",
    "away_opp_G/Sh",
    "away_opp_G/SoT",
    "away_opp_Dist",
    # 'away_opp_npxG',
    # 'away_opp_npxG/Sh',
    # 'away_opp_G-xG',
    # 'away_opp_np:G-xG',
    # 'away_opp_Att',
    # 'away_opp_Cmp',
    "away_opp_TB",
    # 'away_opp_Sw',
    # 'away_opp_Crs',
    # 'away_opp_CK',
    "away_opp_SCA",
    "away_opp_Poss",
    "away_opp_Succ",
    "away_opp_Succ%",
    # 'away_opp_CrdY',
    # 'away_opp_CrdR',
    "away_opp_Recov",
]

selected_stats = {
    "shooting": [
        "Sh",
        "SoT",
        "SoT%",
        "G/Sh",
        "G/SoT",
        "Dist",
        # 'npxG',
        # 'npxG/Sh',
        # 'G-xG',
        # 'np:G-xG',
    ],
    "passing_types": [
        # 'Att',
        # 'Cmp',
        "TB",
        # 'Sw',
        # 'Crs',
        # 'CK'
    ],
    "gca": ["SCA"],
    "possession": ["Poss", "Att", "Succ", "Succ%"],
    "misc": [
        # 'CrdY',
        # 'CrdR',
        "Recov",
    ],
}

strategy = "bankroll_pct"
