filtered_cols = [
        'home_team_xg',
        'home_team_score',
        'home_opp_score',
        'home_opp_xg',
        'home_team_Sh',
        'home_team_SoT',
        'home_team_SoT%',
        'home_team_G/Sh',
        'home_team_G/SoT',
        'home_team_Dist',
        'home_team_SCA',
        'home_opp_Sh',
        'home_opp_SoT',
        'home_opp_SoT%',
        'home_opp_G/Sh',
        'home_opp_G/SoT',
        'home_opp_Dist',
        'home_opp_SCA',
        'away_team_xg',
        'away_team_score',
        'away_opp_score',
        'away_opp_xg',
        'away_team_Sh',
        'away_team_SoT',
        'away_team_SoT%',
        'away_team_G/Sh',
        'away_team_G/SoT',
        'away_team_Dist',
        'away_team_SCA',
        'away_opp_Sh',
        'away_opp_SoT',
        'away_opp_SoT%',
        'away_opp_G/Sh',
        'away_opp_G/SoT',
        'away_opp_Dist',
        'away_opp_SCA',
    ]

selected_stats = {
    'shooting': [
        'Sh',
        'SoT',
        'SoT%',
        'G/Sh',
        'G/SoT',
        'Dist',
    ],
    'gca': [
        'SCA'
    ],
}
 